### ISSUE TITLE
Received messages from Campfire that start with `:` are cut off

### ISSUE THREAD

**Issue by alindeman** [zerowidth/camper_van#16]
```
(22:44:20) < andy_lindeman> groovebot: ruby me puts ":)"
(22:44:26) < groovebot> )
```

I expected a smiley `:)`

I think it has something to do with this line: https://github.com/aniero/camper_van/blob/081b1e66f5d3f14fb3332ae79b0b6b0da12e50b5/lib/camper_van/server_reply.rb#L85. I think removing the conditional would fix it--and I don't think it's problematic to add `:` as a prefix to the last argument in an IRC command, even if there is no space--but I'm not totally sure.

Thoughts?

**Comment by alindeman** [comment]
Any thoughts @aniero? I'd be happy to help fix if you think I'm on the right track.

**Comment by zerowidth** [comment]
It's the right area, but I think some of the replies need the : on the last argument, but not _all_. I'm looking at splitting these up into separate methods for each case.
