### ISSUE TITLE
Binding Failure?

### ISSUE THREAD

**Issue by kylescottmcgill** [zerowidth/camper_van#20]
Hi Aniero,

Do you happen to know anything about the below issue?

``` bash
kyle@Kyles-MacBook-Pro:s000 ~❯ camper_van --log-level debug
2012-11-05 22:09:53  8723  INFO CamperVan : starting server on 127.0.0.1:6667
2012-11-05 22:09:55  8723  INFO CamperVan : got connection from 127.0.0.1
2012-11-05 22:09:55  8723 DEBUG CamperVan : irc -> PASS subdomain:apikey
2012-11-05 22:09:55  8723 DEBUG CamperVan : irc -> NICK Kyle
2012-11-05 22:09:55  8723 DEBUG CamperVan : irc -> USER Kyle 0 * Kyle
2012-11-05 22:09:55  8723  INFO CamperVan : performing request to https://subdomain.campfirenow.com/users/me.json
dyld: lazy symbol binding failed: Symbol not found: _yajl_set_static_value
  Referenced from: /Users/kyle/.rvm/gems/ruby-1.9.3-p286/gems/yajl-ruby-0.7.9/ext/yajl/yajl.bundle
  Expected in: flat namespace

dyld: Symbol not found: _yajl_set_static_value
  Referenced from: /Users/kyle/.rvm/gems/ruby-1.9.3-p286/gems/yajl-ruby-0.7.9/ext/yajl/yajl.bundle
  Expected in: flat namespace

[1]    8723 trace trap  camper_van --log-level debug
```

Thanks in advance!

Kyle

**Comment by kylescottmcgill** [comment]
Also here are the current Gems installed etc

``` bash

kyle@Kyles-MacBook-Pro:s000 ~❯ gem dependency camper_van
Gem camper_van-0.0.6
  eventmachine (~> 0.12.10)
  firering (~> 1.2.0)
  logging (~> 1.5.1)
  rake (>= 0, development)
  trollop (~> 1.16.2)

```

**Comment by kylescottmcgill** [comment]
Similar issue specified ~> https://github.com/defunkt/resque/issues/600 , Issue relating to Ruby Build on Mac OS X

**Comment by greggroth** [comment]
Can you expand on why you closed this?  Did you find a solution?  I'm having the same issue now.

**Comment by kylescottmcgill** [comment]
Hi @greggroth yes i was having an issue with compiling yajl-ruby on mac, clang wasn't doing something right at the time. See here: https://github.com/resque/resque/issues/600

My recommendation is to find a suitable build that does infact compile properly, then this should work. I havn't tried since i had the above issue. However if you get stuck I can give it another go to find out what versions are needed in order to get camper_van running.

**Comment by greggroth** [comment]
It does appear to be fixed in yajl-ruby 1.1.0, so I've submitted a PR to firering (https://github.com/EmmanuelOga/firering/pull/20) to update it's dependency to use 1.1.0 rather than 0.7.6.  Once/If that is merged, I'll open a PR for camper_van to use the updated version of firing.

**Comment by zerowidth** [comment]
:thumbsup: thanks

**Comment by nomicode** [comment]
Woo hoo, looks like your PR was merged. I'm experiencing the same bug.

Is there a workaround for the time being?

**Comment by zerowidth** [comment]
Still need a released version of the firering gem...
