### ISSUE TITLE
Ability to daemonize camper_van

### ISSUE THREAD

**Issue by yorickpeterse** [zerowidth/camper_van#30]
Currently camper_van always runs in the foreground and doesn't create any PID files. This in turn makes it a bit more tricky to run and monitor it (e.g. using Monit) unless you create a wrapper script. It would be nice if camper_van could daemonize itself (e.g. by specifying the `-d/--daemon` flag) and create a PID file (specified using another option)`.

**Comment by zerowidth** [comment]
That seems reasonable to me. I'm not really actively maintaining this though, aside from bugfixes &c... if you have suggestions for a library to use for supporting daemonization, I'm all ears.

**Comment by yorickpeterse** [comment]
Seeing how the change would be fairly trivial (no need for a daemon library) I'll see if I can take a closer look at it tonight.

**Comment by zerowidth** [comment]
Well, there's the whole fork/fork/detach stuff to be a good citizen when running as a daemon, but go for it! Thanks!

**Comment by zerowidth** [comment]
closed in #31
