### ISSUE TITLE
znc-push is not working with camper_van for me

### ISSUE THREAD

**Issue by danrabinowitz** [zerowidth/camper_van#39]
I have camper_van running on my server, and znc connects to it. I'm trying to get znc-push to notify my when there's activity in certain Campfire rooms.

Currently I'm seeing this message in the camper_van output:
INFO CamperVan : ignoring irc command {:ison=>["*push"]}: no handler

I haven't looked into this much yet.

**Comment by zerowidth** [comment]
This is in ircd.rb. Do you have any information as to what znc-push does and how it's configured? Is it via IRC commands? And what is the expected input/output?

**Comment by danrabinowitz** [comment]
I finally got to work on this more yesterday, and it turns out it was user error. I got znc-push working fine. There are still those INFO messages about ignoring the irc command, but it doesn't seem to cause any issues.

Thanks.  Hope you're well.
