### ISSUE TITLE
Yajl problems on OSX 10.9

### ISSUE THREAD

**Issue by vincentwoo** [zerowidth/camper_van#48]
```
2014-02-19 16:59:36  7469  INFO CamperVan : performing request to https://everlane.campfirenow.com/users/me.json
dyld: lazy symbol binding failed: Symbol not found: _yajl_set_static_value
  Referenced from: /Users/vwoo/.gem/ruby/2.1.0/gems/yajl-ruby-0.7.9/ext/yajl/yajl.bundle
  Expected in: flat namespace

dyld: Symbol not found: _yajl_set_static_value
  Referenced from: /Users/vwoo/.gem/ruby/2.1.0/gems/yajl-ruby-0.7.9/ext/yajl/yajl.bundle
  Expected in: flat namespace
```

I'm using ruby 2.0.0

**Comment by wstucco** [comment]
Same issue here.  
My solution is pretty hardcore and I won't suggest anyone to use it. 
I simply linked `/Library/Ruby/Gems/2.0.0/gems/yajl-ruby-0.7.9` to `yajl-ruby-1.2.0`  
It works that way.

**Comment by zerowidth** [comment]
Do I just need to bump the yajl dependency to fix this?

**Comment by vincentwoo** [comment]
I suspect as much, yes.

**Comment by wstucco** [comment]
it should be enough.

**Comment by jjasghar** [comment]
:+1: the symlink worked for me. yajl-ruby-0.7.9 to yajl-ruby-1.1.0, total hack. :'( ruby-2.0.0-p195

**Comment by elia** [comment]
@wstucco you a bad person

**Comment by wstucco** [comment]
@elia I know, I'm sorry

**Comment by zerowidth** [comment]
yajl is a dependency of firering. firering's dependencies have been updated but there isn't a new gem released yet. I've seconded a request for a new release in https://github.com/EmmanuelOga/firering/issues/21

**Comment by lunks** [comment]
A new firering version has been released, closing this issue.
