### ISSUE TITLE
[Enhancement] Multiple campfire connections

### ISSUE THREAD

**Issue by jjasghar** [zerowidth/camper_van#49]
I have a personal campfire account and a work one. It seems pretty logical to be able to use multiple ports for multiple connections. 6667 6668 6669 etc.

Thoughts?

**Comment by zerowidth** [comment]
Simply open a second connection to camper_van with a different subdomain/API key pair and it should work fine.

**Comment by jjasghar** [comment]
Worked :) I'd add this to the docs as an FYI. I can if you'd like.

**Comment by jjasghar** [comment]
I wrote this up: https://github.com/zerowidth/camper_van/pull/50
