### ISSUE TITLE
Can't install camper_van on OSX 10.8.5

### ISSUE THREAD

**Issue by vinodkone** [zerowidth/camper_van#51]
➜  ✗ rvm use 2.0.0  
Using /opt/twitter/rvm/gems/ruby-2.0.0-p353
➜  ✗ gem install camper_van 
Building native extensions.  This could take a while...
ERROR:  Error installing camper_van:
    ERROR: Failed to build gem native extension.

```
/opt/twitter/rvm/rubies/ruby-2.0.0-p353/bin/ruby extconf.rb
```

creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling yajl.c
yajl.c:33:10: fatal error: 'api/yajl_parse.h' file not found
# include "api/yajl_parse.h"

```
     ^
```

1 error generated.
make: **\* [yajl.o] Error 1

make failed, exit code 2

Gem files will remain installed in /opt/twitter/rvm/gems/ruby-2.0.0-p353/gems/yajl-ruby-0.7.9 for inspection.
Results logged to /opt/twitter/rvm/gems/ruby-2.0.0-p353/extensions/x86_64-darwin-12/2.0.0-static/yajl-ruby-0.7.9/gem_make.out

**Comment by zerowidth** [comment]
Looks like a similar issue as in #48. Still waiting on an upstream update of fire_ring.
