### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by dideler** [zerowidth/camper_van#56]
![](http://i1.kym-cdn.com/photos/images/newsfeed/000/234/786/bf7.gif)

Maybe someone can help me out and the README or wiki can be improved.

The public room I want to join is https://assemblyhq.campfirenow.com/room/578218.
My IRC client is weechat. 

> set up a connection to localhost:6667

Using `/connect localhost 6667` didn't work.
So I added a new server as `/server add localhost localhost/6667`.

Then I opened my `~/.weechat/irc.conf` file and scrolled down to the new localhost server settings. Here's what I have so far

![image](https://cloud.githubusercontent.com/assets/497458/3005554/9c71b67c-dde7-11e3-9856-12a566234d20.png)

Am I on the right track? Where do I find the API key?

**Comment by Fusselwurm** [comment]
you can see your API key on https://assemblyhq.campfirenow.com/member/edit

**Comment by dideler** [comment]
@Fusselwurm that link brings me to a login, but I don't have an account and I don't see a sign up option anywhere. I can join the assemblyhq room via this link https://assemblyhq.campfirenow.com/1283b, which doesn't require me to create an account (just need a nick to join).

**Comment by Fusselwurm** [comment]
@dideler cant help you, then. :disappointed:

**Comment by zerowidth** [comment]
@dideler camper_van only works with authenticated connections... if you can figure out a way to talk to the campfire API without an API key, it could probably work with anonymous users like that link above.

**Comment by dideler** [comment]
Thanks for the help @zerowidth and @Fusselwurm. I'm going to close this issue since I'd rather use something else than spend any more time on this.
